<?php
/**
 * Created by PhpStorm.
 * User: yifeng
 * Date: 2017/12/16
 * Time: 23:41
 */

namespace app\index\controller;


use think\Controller;

class Common extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cate=$this->getcate();
        $notice=$this->getNotice();
        //获取右侧栏目推荐文章
        $hot_articles=$this->get_hot_articles();
        //获取右侧栏目点击量文章
        $click_articles=$this->get_click_articles();
        //获取右侧栏目标签
        $tagsData=$this->get_tags();
        //获取右侧友情链接
        $linksData=$this->get_typelinks();
        //获取当前所访问一级栏目标识
        $currcontroller=request()->controller();
        $currtype=$this->getcurrtype($currcontroller);
        //获取网站配置信息
        $config=db('config')->field('config')->find();
        //解码配置信息
        $config=json_decode($config['config'],true);
        //判读网站状态
        if(!isset($config['state'])){
            $config['state']=0;
        }
        $this->checkweb($config['state'],$config['closeinfo']);
        $this->assign([
            'cate'=>$cate,
            'noticeData'=>$notice,
            'hot_articles'=>$hot_articles,
            'click_articles'=>$click_articles,
            'tagsData'=>$tagsData,
            'linksData'=>$linksData,
            'currtype'=>$currtype,
            'config'=>$config,
            'currtyurl'=>$_SERVER['SERVER_NAME']
        ]);
    }

    /**
     * 获取导航栏目
     * @return false|\PDOStatement|string|\think\Collection
     */
    private function getcate(){
        $res=db('category')->where('pid',0)->where('isshow',1)->order('sort desc,id Asc')->field('id,name,type,stype,url')->select();
        foreach ($res as $k=>$v){
            $res_child=db('category')->where('pid',$v['id'])->where('isshow',1)->order('sort desc,id Asc')->field('id,name,type')->select();
            $res[$k]['child']=$res_child;
        }
        return $res;
    }

    /**
     * 获取网站公告
     * @return false|\PDOStatement|string|\think\Collection
     */
    private function getNotice(){
        $time=time();
        $res=db('notice')
            ->where('is_show',1)
            ->where('show_time','>',$time)
            ->order('sort desc,id Asc')
            ->field('id,title,show_time')
            ->select();
        return $res;
    }

    /**
     * 获取右侧栏目推荐文章
     * @return false|\PDOStatement|string|\think\Collection
     */
    private function get_hot_articles(){
        $res=db('article')
            ->order('sort desc,id desc')
            ->field('id,title,click_num,cmt_count')
            ->limit(5)
            ->select();
        return $res;
    }
    /**
     * 获取右侧栏目点击量文章
     * @return false|\PDOStatement|string|\think\Collection
     */
    private function get_click_articles(){
        $res=db('article')
            ->order('click_num desc,id desc')
            ->field('id,title,click_num,cmt_count')
            ->limit(10)
            ->select();
        return $res;
    }
    /**
     * 获取右侧标签管理
     * @return false|\PDOStatement|string|\think\Collection
     */
    private function get_tags(){
        $res=db('tags')
            ->order('sort desc,id ASC')
            ->field('tname,id')
            ->select();
        return $res;
    }

    /**
     * 获取右侧友情链接管理
     * @return false|\PDOStatement|string|\think\Collection
     */
    private function get_typelinks(){
        $time=time();
        $res=db('typelink')
            ->where('is_show',1)
            ->where('show_time','>',$time)
            ->order('sort desc,id ASC')
            ->field('name,url')
            ->select();
        return $res;
    }

    private function getcurrtype($controller){
        switch ($controller){
            case 'Index':
                return 0;
            case 'Comprofile':
                return 1;
            case 'Service':
                return 2;
            case 'Technical':
                return 3;
            case 'Operation':
                return 4;
            case 'News':
                return 5;
            case 'Contactus':
                return 6;
            case 'Cases':
                return 7;
            case 'Education':
                return 8;
            default:
                return 0;
        }
    }


    private function checkweb($state,$info="网站已关闭"){
        if($state!=1){
            header('Content-Type:text/html;charset=utf-8');
            echo $info;
            exit;
        }
    }
    //左侧子栏目列表
    protected function getchild($mark='about'){
        $res_pid=db('category')->where('mark',$mark)->field('id')->find();
        $res=db('category')->where('pid',$res_pid['id'])->field('id,name,type')->select();
        return $res;
    }


    //面包屑导航

    public function position($cid){//传递当前栏目id
        static $pos=array();//创建接受面包屑导航的数组
        if(empty($pos)){//哦，这个就比较重要了，如果需要把当前栏目也放到面包屑导航中的话就要加上
            $cates=db('category')->field('id,name,pid')->find($cid);
            $pos[]=$cates;
        }
        $data=db('category')->field('id,name,pid')->select();//所有栏目信息
        $cates=db('category')->field('id,name,pid')->find($cid);//当前栏目信息
        foreach ($data as $k => $v) {
            if($cates['pid']==$v['id']){
                $pos[]=$v;
                $this->position($v['id']);}
        }
        return array_reverse($pos);
    }

    
    //获取当前位置
    //首页>关于我们>公司简介
    /**
     * @param $id 最小级别的栏目Id,根据这个id获取到它的所有上级分类
     */
//    protected function getlocation($id){
//        $cate=db('category')->where('id',$id)->field('id,name,pid')->find();
//        $arr=[];
//        if($cate){
//            $arr[]=$cate['name'];
//            if($cate['pid']!=0){
//                $pre_cate=$this->getlocation($cate['pid']);
//                $arr=array_merge($pre_cate,$arr);
//            }
//            return $arr;
//        }
//    }



}